
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class itemsearch extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public itemsearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        filter_btn = new javax.swing.JButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        viewrecordbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setForeground(new java.awt.Color(153, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Name of the Item", "Item type", "Received From", "Received on Date", "Warehouse Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH PRODUCTS");
        jLabel1.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Print Invoice for Dispatch");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Filters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel1.setFocusable(false);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(153, 0, 0));
        jRadioButton1.setText("Name of the Product");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setEnabled(false);
        jRadioButton1.setOpaque(true);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(153, 0, 0));
        jRadioButton2.setText("Product ID");
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton2.setOpaque(true);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(153, 0, 0));
        jRadioButton3.setText("Received From");
        jRadioButton3.setEnabled(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(153, 0, 0));
        jRadioButton4.setText("Received on Date");
        jRadioButton4.setEnabled(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(153, 0, 0));
        jRadioButton5.setText("Warehouse Number");
        jRadioButton5.setEnabled(false);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Filter");
        jLabel3.setOpaque(true);

        jTextField1.setEditable(false);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        filter_btn.setBackground(new java.awt.Color(255, 255, 204));
        filter_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        filter_btn.setForeground(new java.awt.Color(153, 0, 0));
        filter_btn.setText("Apply Filter");
        filter_btn.setContentAreaFilled(false);
        filter_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filter_btn.setOpaque(true);
        filter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_btnActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 204));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(153, 0, 0));
        jRadioButton6.setText("Product Type");
        jRadioButton6.setEnabled(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        viewrecordbutton.setBackground(new java.awt.Color(255, 255, 203));
        viewrecordbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewrecordbutton.setForeground(new java.awt.Color(153, 0, 0));
        viewrecordbutton.setText("View Records");
        viewrecordbutton.setContentAreaFilled(false);
        viewrecordbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewrecordbutton.setOpaque(true);
        viewrecordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrecordbuttonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon1.jpg"))); // NOI18N
        jButton3.setText("Go Back");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(viewrecordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(viewrecordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        String a=jLabel3.getText();
        jLabel3.setText(a+" by Warehouse Number");
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        String a=jLabel3.getText();
        jLabel3.setText(a+" by Date of Receiving");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        String a=jLabel3.getText();
        jLabel3.setText(a+" by Received From");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        String a=jLabel3.getText();
        jLabel3.setText(a+" by Product ID");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        String a=jLabel3.getText();
        jLabel3.setText(a+" by Name");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void filter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        String filter=jTextField1.getText();
        if(jRadioButton1.isSelected()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table WHERE item_name='"+filter+"';";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(jRadioButton2.isSelected()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table WHERE item_id='"+filter+"';";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(jRadioButton3.isSelected()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table WHERE received_from='"+filter+"';";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
       else if(jRadioButton4.isSelected()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table WHERE received_date='"+filter+"';";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else if(jRadioButton5.isSelected()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table WHERE warehouse_id='"+filter+"';";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else  if(jRadioButton6.isSelected()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table WHERE product_type='"+filter+"';";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_filter_btnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void viewrecordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrecordbuttonActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        try{
                Class.forName("java.sql.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/warehouse_management?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
                Statement stmt =con.createStatement();

                String qry="SELECT * FROM item_table";

                ResultSet res = stmt.executeQuery(qry);
                while(res.next()){
                    String itemid=res.getString("item_id");
                    String name=res.getString("item_name");
                    String type=res.getString("item_type");
                    String rcvfrm=res.getString("received_from");
                    String rcvdate=res.getString("received_date");
                    String wid=res.getString("warehouse_id");
                    model.addRow(new Object[]{itemid,name,type,rcvfrm,rcvdate,wid});
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
    }//GEN-LAST:event_viewrecordbuttonActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        String a=jLabel3.getText();
        jLabel3.setText(a+" by Product Type");
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TableModel model = jTable1.getModel();
        int i =jTable1.getSelectedRow();
        String id = model.getValueAt(i,0).toString();
        String name=model.getValueAt(i, 1).toString();
        String type=model.getValueAt(i, 2).toString();
        String rcv=model.getValueAt(i, 3).toString();
        String dor=model.getValueAt(i, 4).toString();
        
      print_invoice pi=new print_invoice();
      pi.idfield.setText(id);
      pi.namefield.setText(name);
      pi.typefield.setText(type);
      pi.rcvfield.setText("From :- "+rcv+" || Date :- "+dor);
      
      pi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton filter_btn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton viewrecordbutton;
    // End of variables declaration//GEN-END:variables
}
